# Project: 项目1
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o zigbee链表测试文件/Test_zigbeeList.o
LINKOBJ  = main.o zigbee链表测试文件/Test_zigbeeList.o
LIBS     = -L"D:/DEV-C/Software/Dev-Cpp/MinGW64/lib" -L"D:/DEV-C/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/include" -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/include" -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/DEV-C/Software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 测试.exe
CXXFLAGS = $(CXXINCS) -pg
CFLAGS   = $(INCS) -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

zigbee链表测试文件/Test_zigbeeList.o: zigbee链表测试文件/Test_zigbeeList.c
	$(CC) -c zigbee链表测试文件/Test_zigbeeList.c -o zigbee链表测试文件/Test_zigbeeList.o $(CFLAGS)
